desired_data:
  - nuplan_test

cache_location: "/inspire/hdd/project/roboticsystem2/wangcaojun-240208020180/repo-wcj/trajdata/datasets2"

incl_vector_map: true
rebuild_cache: false
rebuild_maps: false
require_map_cache: false
num_workers: 1
desired_dt: 0.5
verbose: true

data_dirs:
  nuplan_test: "/inspire/hdd/project/roboticsystem2/public/nuplan/dataset/nuplan-v1.1"

# scene_indices: [0]

